version: "3.1"

nlu:
- intent: agendar_compromisso
  examples: |
    - Fazer apresentação no centro do Rio às 16h
    - Reunião com o time amanhã às 11h
    - Consulta médica dia 24/07 às 14:30
    - Aulas de yoga toda terça às 18h
    - Encontro semanal de planejamento segunda-feira às 9h
    - Reunião com o João dia 20 às 14h
    - Marcar dentista dia 21 às 10h 
    - reunião com cliente às 15h
    - Dia 22 às 13h terapia
    - call c time 25 14h
    - Remarcar reunião para dia 24 ou 25 às 16h
    - Agendar teste de direção para sexta-feira 9h no DETRAN
    - Visita técnica dia 15/08 às 10:30 na fábrica
    - Reunião de pais próxima quarta 14h na escola
    - Entrevista com recrutadora após amanhã 11h
    - Apresentação comercial no shopping 15h 28/07
    - eu vou na feira de são cristovão hoje, é aniversário de uma amg, ela deixou chamar geral, ses tão afim de ir?
    - Se a gente for pra um lugar mais perto\nTipo barkana\nLa tem dose dupla\nE karaoke\nDaì acaba tipo 23h\nMeia noite
    - Podemos sim, está marcado amanhã 12h então

- intent: criar_tarefa_sem_data
  examples: |
    - Estou preparando um orçamento e te envio até sexta-feira
    - Preciso revisar aquele relatório quando der tempo
    - Me lembro de desenhar o diagrama antes da reunião
    - Comprar ração para o cachorro esta semana
    - Criar post para o blog em breve
    - Sexta comprei uma caixa pra gente comemorar
    - Falar com a terapeuta depois
    - Traduzir o contrato até quarta
    - Formatar slides antes do almoço
    - Pesquisar voos para SP nesse mês
    - Enviar documentos até o fim do dia
    - Testar o aplicativo novo quando possível
    - remedio de maya

- intent: associar_gatilho_contextual
  examples: |
    - Quando for no mercado, traz tomate
    - Se passar na farmácia, compra meu remédio
    - Ao chegar em casa, ligar para a Maria
    - Se tiver brócolis no supermercado, compra pra mim
    - Quando voltar da academia, me avisa
    - Ao terminar a reunião, enviar e-mail para TI
    - Se vir café em promoção no atacadão, compra 3 pacotes
    - Quando sair do trabalho, pegar encomenda na farmacia
    - Ao passar na livraria, ver livro de Python
    - Se chover amanhã, cancelar o piquenique

- intent: agradecimento
  examples: |
    - Obrigado
    - Valeu, amigo
    - Show, era isso mesmo
    - Perfeito, obrigado!
    - Obrigada pela ajuda
    - Top demais!
    - Brigadão!
    - Salvou minha vida
    - Maravilha, obrigada!
    - Valeu pelo help
    - Obrigado RB M\u00f3veis, voc\u00ea terminou de pagar o valor referente ao projeto de Mariana Abra\u00e3o.
    - poha brigadão viado, qualquer coisa falo cntg sim e precisando de alguma coisa pode falar comigo tbm
    - Olá, Grazi! Bom dia, demorei um pouco a responder porque estava pensando a respeito.\\n\\nAgradeço novamente pela oportunidade e pelos detalhes! Analisei os requisitos e vejo um alinhamento direto com minhas experi\u00eancias mais recentes em IA Generativa.\\n\\nEmbora minha trajetória seja focada em engenharia de software aplicada a IA, as tecnologias que vocês buscam é LangChain, RAG e Python para GenAI que é exatamente meu principal campo de atuação e estudo.\\n\\nMinha pretensão salarial para o modelo CLT é de R$ 7.000,00.\\n\\nEstou confiante de que posso contribuir rapidamente com a equipe no desenvolvimento de soluções com LLMs e estou aberto a propostas. Fico a sua disposição!

- intent: outros
  examples: |
    - Sei lá
    - Doideira
    - Caramba
    - Hmmmm
    - Aff...
    - Nossa senhora
    - Puts vida
    - Eita
    - Hã?
    - Faaala Vitinho
    - Tudo jóia por aí
    - Perfeitoo
    - se eu quiser aproveitar nessa validação adicionar mais um e-mail vc faz por este mesmo valor
    - acrescenta
    - primeiramente feliz aniversário
    - posso levar 4-5 cabeças vou ver se eles querem ir
    - conforme for se não puder
    - dps tento pelo menos passar lá para dar um oi vai ser onde mesmo
    - tô descendo Commitar
    - Tem sugestão
    - Mano, vai pra Lapa, eu tô tranquilo vejo vcs no domingo
    - Por aì
    - 👴🏻 <- pai oh
    - nada fechado
    - Eu sei q vc ta tranquilo
    - É isso q to tentando solucionar
    - nada fechado
    - https://vm.tiktok.com/ZMStpn3Pm/
    - Tô em casa tropa
    - Setlist: \n\nSweet dreams\nHeart-shaped box \nSem futuro\nCities in dust\nParanóia\nMan in the box\nEspanque um nazipardo\nVoz do racismo\nBring me to life\nNada pelo que lutar\nNa sua estante
    - CONFIG_SESSION_PHONE_VERSION=2.3000.1025062854
    - sim, da outra vez funcionava o qrcode, dessa vez n\u00e3o ta indo, mas a instala\u00e7\u00e3o antes foi com base no repo deles usando as mesmas configs, dessa to fazendo com base no docker-file, mas eu que instalei o redis, eu que instalei o postgres e to add os envs, deve estar faltando alguma coisa
    - bom dia mano, P\u00f4 consegui fazer o lance do mercadopago, a integra\u00e7\u00e3o \u00e9 razoavelmente tranquila de fazer
    - eu j\u00e1 resolvi a parada do redis, da para colocar o nome do container tbm, q ele pega o localhost de l\u00e13
    - esse erro tava acontecendo e era com rela\u00e7\u00e3o a versao
    - Esse ultimo eu mudei, esse aviso \u00e9 para voc\u00ea e n\u00e3o para o fornecedor
    - Email de dev:\\njucareformasdev@gmail.com\\nJucaReformasDev!123\\n\\nDemais senhas:\\nJucaReformasDev@123\\n* Hostinger\\n* Github
    - 2067
    - ela deve estar dirigindo
    - Achei q era 2036 e n\u00e3o t\u00e1 indo
    - pro cliente falei que ta na cloud kkkkkkkkk
    - pra medir produtividade
    - cria um pra fuder trabalhador
    - Ah, tu que ta na pira de pegar freela, se liga
    - rpa tem muita mercado
    - Me passaram esses dias, não conhecia não, mas ele deixa tu usar a API do whatsapp 0800
    - para de forçar isso
    - até chegar no lider técnico
    - fiz os bglh, cheguei na entrevista, mlk 1 passo é só passar pelo RH, caralho eu sei o bglh
    - não deram resposta ainda não, mas pelo sentimento na entrevista cai de otário
    - faz, foi forte tá, dps pelo esporte vou fazer um agente que faz aquele processo e compartilho contigo, preciso aprender a fazer deep search com agente em código
    - no pior dos casos tenho um prá pagamento para Saas pronto kkk
    - ah ta, a regra não é do mercado pago, mas da loja, ela não deixa guardar dados do usuário e você precisaria guardar para fazer o pagamento, é isso?
    - qualquer duvida pode falar cmg sobre mobile