version: "3.1"

nlu:
- intent: agendar_compromisso
  examples: |
    - Gostaria de agendar uma reunião para amanhã de manhã.
    - Marcar um café com o João na sexta-feira.
    - Preciso de um horário com a equipe de marketing na semana que vem.
    - Vamos combinar uma call para discutir o projeto?
    - Agende uma demonstração do produto para o cliente na terça às 15h.
    - Pode marcar um almoço com os investidores?
    - Quero reservar a sala de reuniões para quarta-feira, depois do almoço.
    - Adicionar um evento no meu calendário: alinhamento com a diretoria.
    - Marque uma conversa rápida com a Maria para hoje no fim da tarde.
    - Registrar um compromisso para o dia 20 deste mês.
    - É possível agendar uma visita técnica para a próxima segunda?
    - Vamos marcar a apresentação para o dia 10, às 10h.
    - Crie um evento chamado 'Revisão Semanal' para toda sexta-feira.
    - Preciso encaixar uma reunião urgente hoje.
    - Agendar uma consulta médica para a semana que vem.
    - Marcar entrevista com o candidato amanhã às 14h.
    - Combine um happy hour com o pessoal na quinta.
    - Quero agendar a defesa do meu projeto para o final do mês.
    - Adicione na minha agenda: Treinamento de Vendas no dia 5.
    - Podemos marcar nossa conversa para depois das 18h?
    - Gostaria de agendar um follow-up para daqui a duas semanas.
    - Marcar um bate-papo com o time de design.
    - Por favor, agende a manutenção do servidor para o próximo sábado.
    - Cria um evento no meu calendário para a viagem a São Paulo.
    - Vamos definir uma data para a nossa reunião de planejamento.
    - Anote aí: reunião com o fornecedor na segunda, 9h.
    - Preciso de um slot na sua agenda para falarmos sobre o orçamento.
    - Agende uma reunião com todos os gerentes, por favor.
    - Poderia marcar uma conferência com o escritório de Londres?
    - Registrar na minha agenda: Workshop de Inovação dia 18.
    - Vamos agendar o início do projeto para a primeira semana do mês que vem.
    - Marcar a entrega da proposta para amanhã sem falta.
    - Por favor, encontre um horário para eu falar com a Ana.
    - Agende o kick-off do projeto para terça-feira.
    - Pode marcar um retorno com o cliente para o dia 25?
    - Combine com eles uma reunião para acertar os detalhes.
    - Quero marcar um horário com o departamento financeiro.
    - Adicionar na agenda: Apresentação de resultados trimestrais.
    - Agende uma ligação para mim com o Dr. Silva.
    - Vamos ter uma reunião de alinhamento amanhã cedo.
    - Marque um tempo para revisarmos o contrato.
    - Preciso agendar a avaliação de desempenho da equipe.
    - Crie um convite para a festa de fim de ano da empresa.
    - Agendar um café virtual com a equipe remota.
    - Por favor, agende a calibração dos equipamentos.
    - Marcar uma sessão de brainstorming para o projeto novo.
    - Vamos nos encontrar na quarta para discutir isso?
    - Poderia agendar a passagem da transportadora?
    - Anote um compromisso para mim no dia 30: Fórum de Tecnologia.
    - Preciso reservar a manhã de sexta para focar no relatório.
    - Marque uma reunião com o jurídico para validar o documento.
    - Agendar o onboarding do novo funcionário para segunda-feira.

- intent: criar_tarefa_com_prazo_limite
  examples: |
    - Criar lembrete para entregar o relatório até sexta-feira.
    - Me lembre de comprar o presente da Maria até o dia 20.
    - Adicionar uma tarefa: revisar a apresentação com prazo final para amanhã.
    - Anote aí: preciso pagar a fatura do cartão até a próxima semana.
    - Criar uma tarefa para enviar os documentos com deadline para hoje.
    - Lembrete: finalizar o artigo até o final do mês.
    - Preciso terminar a análise de dados até quarta-feira.
    - Adicionar à minha lista de tarefas: responder o e-mail do cliente até o fim do dia.
    - Crie uma tarefa com o título 'Preparar material' com prazo para 15/09.
    - Não me deixe esquecer de submeter o projeto até a data limite.
    - Anote uma tarefa: ligar para o fornecedor. Prazo: amanhã.
    - Lembrete: atualizar a planilha de custos, a data de entrega é na segunda.
    - Crie a tarefa 'Montar o cronograma' para ser concluída em uma semana.
    - Adicione uma tarefa com vencimento para hoje: validar os novos layouts.
    - Preciso que me lembre de fazer a reserva do hotel até o dia 10.
    - Criar tarefa: pesquisar preços dos voos. Prazo final: esta semana.
    - Anote para mim: devolver os livros na biblioteca até sábado.
    - Definir uma tarefa para 'revisar o código' com prazo de entrega para depois de amanhã.
    - Me lembre de agendar o exame médico. Tenho que fazer isso até o final desta semana.
    - Adicionar na lista de pendências: comprar os ingressos para o show até amanhã.
    - Criar tarefa: escrever o post para o blog com data limite para 25/08.
    - Lembrete com prazo: organizar a pasta de contratos até a próxima sexta-feira.
    - Anote uma nova tarefa: preciso consolidar os feedbacks até o dia 5 do próximo mês.
    - Criar uma tarefa para 'confirmar as presenças' com deadline para a véspera do evento.
    - Me avise para iniciar a campanha de marketing. O prazo máximo é semana que vem.
    - Adicione a tarefa 'desenvolver o protótipo' com vencimento em duas semanas.
    - Preciso concluir o curso online até o final do ano.
    - Crie um lembrete para eu não esquecer de renovar a assinatura até o dia 30.
    - Tarefa: enviar a nota fiscal para o cliente. Prazo: hoje.
    - Lembre-se de me avisar para pagar o aluguel, o vencimento é no dia 10.
    - Adicionar a pendência 'fazer o backup dos arquivos' com data limite para o próximo domingo.
    - Crie a tarefa: 'emitir o relatório de vendas'. O prazo é o último dia útil do mês.
    - Anote aí: preciso finalizar a minha parte do trabalho até quinta à noite.
    - Me lembre de montar a mala para a viagem até amanhã.
    - Adicionar tarefa: limpar a caixa de entrada, com prazo de 3 dias.
    - Criar lembrete para eu estudar para a prova. Data limite é a próxima segunda.
    - Tarefa com deadline: aprovar as férias da equipe até o final da semana.
    - Preciso entregar a documentação até o dia 12, anote isso por favor.
    - Coloque na minha lista: 'verificar o andamento do projeto' com prazo para amanhã à tarde.
    - Crie uma tarefa para mim: 'fazer a declaração de imposto de renda'. Prazo final é em abril.
    - Lembrete: agendar a revisão do carro até o próximo mês.
    - Adicionar tarefa: 'comprar material de escritório'. Data de conclusão: sexta-feira.
    - Anote a tarefa 'organizar os arquivos digitais' com vencimento para daqui a 15 dias.
    - Preciso que me lembre de enviar os convites, a data limite é hoje.
    - Criar uma tarefa para 'pesquisar hotéis'. O prazo para isso é até amanhã.
    - Não posso esquecer de finalizar a minuta do contrato até o fim da tarde.
    - Adicionar na minha lista de coisas a fazer: 'planejar o conteúdo da semana'. Fazer até domingo.
    - Crie um lembrete para 'atualizar meu currículo' com prazo até o final de semana.
    - Tarefa urgente: 'corrigir o bug em produção'. O prazo é hoje.
    - Me lembre de pagar a matrícula da faculdade até o quinto dia útil.